name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

#     - name: Build with Gradle
#       run: ./gradlew build
#     - name: Android Build
#       uses: vgaidarji/android-github-actions-build@v1.0.1
#       with:
#         args: "./gradlew assembleDebug"

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug

#    - name: Upload a Build Artifact
#      uses: actions/upload-artifact@v2
#      with:
        # Artifact name
#        name: demo-simpleloginet-artifacts
        # A file, directory or wildcard pattern that describes what to upload
#        path: ./demo-simpleloginet/build/outputs/apk/**
#     - uses: actions/download-artifact@v2
#     - name: Display structure of downloaded files
#       run: ls -R

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./demo-simpleloginet/build/outputs/apk/debug/demo-simpleloginet-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}